server:
#  port: 8080
  port: 8088



spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/birdfarm_swp391?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://localhost:3308/birdfarmshop?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false

    username: root
    password:

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 238128811346-1evcteptub6t5t4qintv8cc0oc7j7q4e.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 688278529825082
            clientSecret: a4d583d56f60c82ceb7ad8f56aab09d7
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v18.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v18.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v18.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
app:
  api:
    version:
      v1: /api/v1
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuthase172485@gmail.com
    password: pziv apyr uaqs iorr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  openapi:
    dev-url: http://localhost:9090
    prod-url: https://localhost:9090
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect